compliance:
  name: Test Compliance # name of compliance
  catalog:
    url: ./pkg/testdata/oscal/reporter-test/catalog.json
  profile:
    url: ./pkg/testdata/oscal/reporter-test/profile.json
  componentDefinition:
    url: ./pkg/testdata/oscal/reporter-test/component-definition.json
policyResources: 
  url: ./pkg/testdata/ocm/policies
policyResults: 
  url: ./pkg/testdata/ocm/policy-results
clusterGroups:
  - name: test-group # name of clusterGroup
    matchLabels:
      environment: test # label's key value pair of clusterlabel
binding:
  compliance: Test Complianc # compliance name
  clusterGroups:
  - test-group # clusterGroup name
target:
  namespace: c2p # namespace to which C2P deploys generated resources