compliance:
  name: Test Compliance # name of compliance
  catalog:
    url: ./pkg/composer/testdata/oscal/catalog.json
  profile:
    url: ./pkg/composer/testdata/oscal/profile.json
  componentDefinition:
    url: ./pkg/composer/testdata/oscal/component-definition.json
policyResources: 
  url: ./pkg/composer/testdata/ocm/policies
policyResults: 
  url: a/b/c
clusterGroups:
  - name: cluster-nist-high # name of clusterGroup
    matchLabels:
      level: nist-high # label's key value pair of clusterlabel
binding:
  compliance: NIST_SP-800-53-HIGH # compliance name
  clusterGroups:
  - cluster-nist-high # clusterGroup name
target:
  namespace: "" # namespace to which C2P deploys generated resources